/*
 * Copyright (c) 2026, Matthijs Möhlmann
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <iostream>

#include "tab_point.h"
#include <sqlpp26/tests/postgresql/all.h>


namespace sql = sqlpp::postgresql;

int main(int, char*[]) {
  try {
    auto db = sql::make_test_connection();

    test::createTabPoint(db);
    const auto t = test::TabPoint{};

    // --- INSERT
    // --------------------------------------------------------------- id is
    // generated by PostgreSQL; only color is required.
    db(insert_into(t).set(t.color = Color::red));
    db(insert_into(t).set(t.color = Color::green));
    db(insert_into(t).set(t.color = Color::blue));

    // --- SELECT
    // --------------------------------------------------------------- row.id is
    // PointId, row.color is Color — no unwrapping at the call site.
    {
      int count = 0;
      for (const auto& row :
           db(select(all_of(t)).from(t).order_by(t.id.asc().nulls_first()))) {
        static_assert(std::is_same_v<decltype(row.id), PointId>);
        static_assert(std::is_same_v<decltype(row.color), Color>);
        ++count;
        require_equal(row.id.value, count);
      }
      require_equal(count, 3);
    }

    // --- UPDATE
    // --------------------------------------------------------------- Filter by
    // PointId, set a new Color.
    db(update(t).set(t.color = Color::blue).where(t.id == PointId{1}));

    {
      for (const auto& row :
           db(select(t.color).from(t).where(t.id == PointId{1}))) {
        require_equal(row.color, Color::blue);
      }
    }

    // --- DELETE
    // --------------------------------------------------------------- Filter by
    // Color — removes all blue rows (id 1 and 3).
    db(delete_from(t).where(t.color == Color::blue));

    {
      int count = 0;
      for (const auto& row : db(select(all_of(t)).from(t))) {
        require_equal(row.color, Color::green);
        ++count;
      }
      require_equal(count, 1);
    }

    // --- PREPARED INSERT
    // ------------------------------------------------------
    {
      auto stmt =
          db.prepare(insert_into(t).set(t.color = sqlpp::parameter(t.color)));
      stmt.parameters.color = Color::red;
      db(stmt);
      stmt.parameters.color = Color::blue;
      db(stmt);
    }

    // --- PREPARED SELECT
    // ------------------------------------------------------ Filter by Color;
    // verify both PointId and Color come back as the right types.
    {
      auto stmt = db.prepare(select(all_of(t)).from(t).where(
          t.color == sqlpp::parameter(t.color)));
      stmt.parameters.color = Color::green;
      for (const auto& row : db(stmt)) {
        static_assert(std::is_same_v<decltype(row.id), PointId>);
        static_assert(std::is_same_v<decltype(row.color), Color>);
        require_equal(row.color, Color::green);
      }
    }

    // --- PREPARED UPDATE
    // ------------------------------------------------------ Filter by PointId,
    // set a new Color.
    {
      auto stmt = db.prepare(update(t)
                                 .set(t.color = sqlpp::parameter(t.color))
                                 .where(t.id == sqlpp::parameter(t.id)));
      stmt.parameters.color = Color::blue;
      stmt.parameters.id = PointId{2};
      db(stmt);
    }

    // --- PREPARED DELETE
    // ------------------------------------------------------ Filter by PointId.
    {
      auto stmt =
          db.prepare(delete_from(t).where(t.id == sqlpp::parameter(t.id)));
      stmt.parameters.id = PointId{2};
      db(stmt);
    }

  } catch (const std::exception& e) {
    std::cerr << "Exception: " << e.what() << std::endl;
    return 1;
  }
  return 0;
}
